

server:
  port: 80

http:
  maxTotal: 20 #最大连接数
  defaultMaxPerRoute: 20 #并发数
  connectTimeout: 1000 #创建连接的最长时间
  connectionRequestTimeout: 500 #从连接池中获取到连接的最长时间
  socketTimeout: 10000 #数据传输的最长时间
  staleConnectionCheckEnabled: true #提交请求前测试连接是否可用

#力谱云参数
lipuyun:
  masterKey: M3FmTXNIR0tlNDB0V2ZPRGRHLWxtUQ
  restApiKey: UEYtbldodkZmbnc3TUZaaENPMjdZUQ
  appId: 5bc15cf20351cb0007a67fb1

spring:
  application:
    name: integral
  profiles:
    active: @profileActive@